# Generated by Django 5.0.2 on 2024-02-18 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('brands', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=50)),
                ('categories', models.CharField(max_length=200)),
                ('protein_per_100g', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('carbs_per_100g', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('fats_per_100g', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('kcal_per_100g', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('product_type', models.CharField(choices=[('None', 'None'), ('lactate', 'Lactate'), ('carne', 'Carne'), ('legume', 'Legume'), ('fructe', 'Fructe')], default='None', max_length=20)),
                ('user_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('brands', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=50)),
                ('categories', models.CharField(max_length=200)),
                ('protein_per_100g', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('carbs_per_100g', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fats_per_100g', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('kcal_per_100g', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('product_type', models.CharField(choices=[('None', 'None'), ('lactate', 'Lactate'), ('carne', 'Carne'), ('legume', 'Legume'), ('fructe', 'Fructe')], default='None', max_length=20)),
                ('user_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
            ],
        ),
    ]
