# Generated by Django 5.0.2 on 2024-02-21 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WellnessCorner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketitem',
            name='api_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='WellnessCorner.apiproduct'),
        ),
        migrations.AlterField(
            model_name='basketitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='WellnessCorner.product'),
        ),
        migrations.AlterField(
            model_name='basketitem',
            name='source',
            field=models.CharField(choices=[('database', 'Database'), ('api', 'API')], max_length=20),
        ),
    ]
