# Generated by Django 5.0.2 on 2024-03-03 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WellnessCorner', '0003_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiproduct',
            name='total_ratings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pendingproduct',
            name='total_ratings',
            field=models.IntegerField(default=0),
        ),
    ]
