# Generated by Django 5.0.2 on 2024-02-21 16:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WellnessCorner', '0003_product_approved_alter_product_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='PendingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('brands', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=50)),
                ('categories', models.CharField(max_length=200)),
                ('protein_per_100g', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('carbs_per_100g', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fats_per_100g', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('kcal_per_100g', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('product_type', models.CharField(max_length=20)),
                ('user_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('allergies', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved', models.BooleanField(default=False)),
                ('superuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='PendingProductApproval',
        ),
    ]
