# Generated by Django 5.0.3 on 2024-03-30 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WellnessCorner', '0004_article_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='ArticleImage',
        ),
    ]
