# Generated by Django 5.0.2 on 2024-02-19 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WellnessCorner', '0004_allergy_user_allergies'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='allergies',
            field=models.TextField(blank=True, null=True),
        ),
    ]
