# Generated by Django 5.0.2 on 2024-03-03 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WellnessCorner', '0004_apiproduct_total_ratings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingproduct',
            name='total_ratings',
        ),
        migrations.RemoveField(
            model_name='pendingproduct',
            name='user_rating',
        ),
        migrations.AddField(
            model_name='product',
            name='total_ratings',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ApiProductRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WellnessCorner.apiproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='apiproduct',
            name='rated_by',
            field=models.ManyToManyField(through='WellnessCorner.ApiProductRating', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProductRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WellnessCorner.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='rated_by',
            field=models.ManyToManyField(through='WellnessCorner.ProductRating', to=settings.AUTH_USER_MODEL),
        ),
    ]
