# Generated by Django 5.0.3 on 2024-03-30 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WellnessCorner', '0005_rename_image_articleimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
