# Generated by Django 5.0.2 on 2024-02-22 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WellnessCorner', '0005_remove_pendingproduct_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiproduct',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pendingproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pending_product_images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
