# Generated by Django 5.0.2 on 2024-03-03 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WellnessCorner', '0005_remove_pendingproduct_total_ratings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiproductrating',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='productrating',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
