# Generated by Django 5.0.3 on 2024-03-31 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WellnessCorner', '0006_article_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
