# Generated by Django 5.0.3 on 2024-05-05 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WellnessCorner', '0007_recipe_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='recipes/'),
        ),
    ]
