# Generated by Django 5.0.2 on 2024-02-23 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WellnessCorner', '0007_remove_apiproduct_image_url_apiproduct_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingproduct',
            name='superuser',
        ),
    ]
