# Generated by Django 5.0.2 on 2024-03-04 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WellnessCorner', '0007_basketitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='basket',
            name='age_confirmation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='basket',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='basket',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
