# Generated by Django 5.0.2 on 2024-02-20 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WellnessCorner', '0007_basket'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Basket',
        ),
    ]
