# Generated by Django 5.0.2 on 2024-03-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WellnessCorner', '0009_basketitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
