# Generated by Django 5.0.2 on 2024-03-05 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WellnessCorner', '0010_alter_basketitem_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Snacks', 'Snacks')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MealApiProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_grams', models.DecimalField(decimal_places=2, max_digits=10)),
                ('api_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WellnessCorner.apiproduct')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WellnessCorner.meal')),
            ],
        ),
        migrations.AddField(
            model_name='meal',
            name='api_products',
            field=models.ManyToManyField(through='WellnessCorner.MealApiProduct', to='WellnessCorner.apiproduct'),
        ),
        migrations.CreateModel(
            name='MealProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_grams', models.DecimalField(decimal_places=2, max_digits=10)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WellnessCorner.meal')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WellnessCorner.product')),
            ],
        ),
        migrations.AddField(
            model_name='meal',
            name='products',
            field=models.ManyToManyField(through='WellnessCorner.MealProduct', to='WellnessCorner.product'),
        ),
    ]
