# Generated by Django 5.0.2 on 2024-03-05 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WellnessCorner', '0013_mealapiproduct_carbs_per_100g_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealapiproduct',
            name='total_calories',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mealproduct',
            name='total_calories',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
