# Generated by Django 5.0.2 on 2024-03-05 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WellnessCorner', '0014_mealapiproduct_total_calories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealapiproduct',
            name='total_calories',
        ),
        migrations.RemoveField(
            model_name='mealproduct',
            name='total_calories',
        ),
    ]
