# Generated by Django 5.0.2 on 2024-03-05 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WellnessCorner', '0015_remove_mealapiproduct_total_calories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='total_calories',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='meal',
            name='total_carbs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='meal',
            name='total_fats',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='meal',
            name='total_proteins',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
