# Generated by Django 5.0.2 on 2024-03-05 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WellnessCorner', '0016_meal_total_calories_meal_total_carbs_meal_total_fats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activity_level',
            field=models.CharField(choices=[('sedentary', 'Sedentary'), ('lightly_active', 'Lightly Active'), ('moderately_active', 'Moderately Active'), ('very_active', 'Very Active'), ('extra_active', 'Extra Active')], default='sedentary', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(default=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='goal',
            field=models.CharField(choices=[('cut', 'Cut'), ('bulk', 'Bulk'), ('maintain', 'Maintain')], default='maintain', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='height',
            field=models.PositiveIntegerField(default=180),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=80, max_digits=5),
            preserve_default=False,
        ),
    ]
