# Generated by Django 5.0.2 on 2024-03-05 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WellnessCorner', '0018_remove_user_activity_level_remove_user_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='daily_calories',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
