# Generated by Django 5.0.1 on 2024-03-07 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WellnessCorner', '0020_userprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingproduct',
            name='user_rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
