# Generated by Django 5.0.2 on 2024-03-09 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WellnessCorner', '0022_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='conditions',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='is_percentage',
        ),
    ]
