# Generated by Django 5.0.2 on 2024-03-09 12:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WellnessCorner', '0023_remove_discount_conditions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
