# Generated by Django 5.0.2 on 2024-03-09 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WellnessCorner', '0024_basket_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='total_price',
        ),
    ]
