# Generated by Django 5.0.2 on 2024-03-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WellnessCorner', '0027_alter_discount_code_alter_discount_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='discount',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='discount',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
