# Generated by Django 5.0.2 on 2024-03-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WellnessCorner', '0028_alter_discount_unique_together_alter_discount_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='discount',
            unique_together={('user', 'code')},
        ),
    ]
