# Generated by Django 5.0.2 on 2024-03-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WellnessCorner', '0030_alter_discount_unique_together_alter_discount_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiproduct',
            name='nutriscore',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='pendingproduct',
            name='nutriscore',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='nutriscore',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
