# Generated by Django 5.0.2 on 2024-03-09 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WellnessCorner', '0034_pendingproduct_saturated_fats_per_100g_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiproduct',
            name='saturated_fats_per_100g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='apiproduct',
            name='sodium_per_100g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='apiproduct',
            name='sugars_per_100g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
